[package]
name = "ricracroe"
version = "0.1.0"
authors = ["Will Page <compenguy@gmail.com>"]
edition = "2018"

[dependencies]
log = { version = "0.4", default-features = true, features = ["std"] }
flexi_logger = "0.13"
tempdir = "0.3"
clap = "2.33"
crossterm = "0.13"
